<?php
/**
 * Asset helper functions.
 *
 * Provides utility functions for working with plugin assets including
 * paths, URLs, versions, and dependencies generated by @wordpress/scripts.
 *
 * @package GunitaPlugin
 */

namespace GunitaPlugin\Helpers;

/**
 * Class Asset
 *
 * This class provides helper functions for working with assets.
 * All methods are static as this is a utility class.
 */
class Asset {

	/**
	 * Get the filesystem path to an asset file.
	 *
	 * @global string GUNITA_PLUGIN_PATH The plugin directory path.
	 *
	 * @param string $file The file name without extension.
	 * @param string $ext  Optional. The file extension. Default empty string.
	 * @return string The full filesystem path to the asset file.
	 */
	public static function get_file_path( string $file, string $ext = '' ): string {
		return GUNITA_PLUGIN_PATH . '/build/' . $file . ( $ext ? '.' . $ext : '' );
	}

	/**
	 * Get the URL to an asset file.
	 *
	 * @global string GUNITA_PLUGIN_URL The plugin directory URL.
	 *
	 * @param string $file The file name without extension.
	 * @param string $ext  Optional. The file extension. Default empty string.
	 * @return string The full URL to the asset file.
	 */
	public static function get_file_url( string $file, string $ext = '' ): string {
		return GUNITA_PLUGIN_URL . '/build/' . $file . ( $ext ? '.' . $ext : '' );
	}

	/**
	 * Get the asset registry data.
	 *
	 * Reads the .asset.php file generated by @wordpress/scripts which contains
	 * version and dependency information.
	 *
	 * @param string $file The file name without extension.
	 * @return array{version?: string, dependencies?: array<string>} The asset registry data.
	 */
	public static function get_file_asset( string $file ): array {
		$asset_file      = $file . '.asset.php';
		$asset_file_path = self::get_file_path( $asset_file );

		// Check if the asset registry file exists.
		if ( ! is_readable( $asset_file_path ) ) {
			// Log the error in debug mode.
			if ( defined( 'WP_DEBUG' ) && WP_DEBUG ) {
				// phpcs:ignore WordPress.PHP.DevelopmentFunctions.error_log_error_log
				error_log(
					sprintf(
						'GunitaPlugin: Asset file not found: %s. Run "pnpm run build" to generate assets.',
						esc_html( $asset_file )
					)
				);
			}

			// Return empty array instead of dying.
			return [
				'dependencies' => [],
				'version'      => GUNITA_PLUGIN_VERSION,
			];
		}

		return require $asset_file_path;
	}

	/**
	 * Get the version of an asset file.
	 *
	 * @global string GUNITA_PLUGIN_VERSION The plugin version.
	 *
	 * @param string $file The file name without extension.
	 * @return string The version string, or plugin version as fallback.
	 */
	public static function get_file_version( string $file ): string {
		$asset = self::get_file_asset( $file );
		return $asset['version'] ?? GUNITA_PLUGIN_VERSION;
	}

	/**
	 * Get the dependencies of an asset file.
	 *
	 * @param string $file The file name without extension.
	 * @return array<string> Array of dependency handles.
	 */
	public static function get_file_dependencies( string $file ): array {
		$asset = self::get_file_asset( $file );
		return $asset['dependencies'] ?? [];
	}
}
